### ISSUE TITLE
[FR] Request from `--support` submission: Add flag for Y-Axis to be log-scale, universally.  

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBB#2769]
Log-scale is commonly used for, among many other uses, viewing long-term charts. Currently, the only way to accomplish this is to use the `line` function from the QA menu, or `candle --plotly`. Log-scales would be particularly useful for digital assets, but it would be nice to switch any chart to a log-scale with a universal argument.

**Comment by jmaslek** [comment]
welp here we go with labeling log scales again 😢 

<img width="787" alt="Screen Shot 2022-10-10 at 9 16 37 PM" src="https://user-images.githubusercontent.com/18151143/194976058-4cc0c4be-4e9e-402b-9137-b6288aae0580.png">

**Comment by deeleeramone** [comment]
Works fine with the line plot. `/qa/line --log`

![Screen Shot 2022-10-10 at 6 45 42 PM](https://user-images.githubusercontent.com/85772166/194978782-8b92a725-de92-48f8-a847-cd474a87c5f9.png)

**Comment by jmaslek** [comment]
i got it 😁

**Comment by deeleeramone** [comment]
and to think that you were worried your PhD was going to go to waste. 🚀
