### ISSUE TITLE
[Bug] stocks/ta/macd. -- Chart style in general

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBB#2963]
The chart font sizes have been off, but this one I had to raise a bug on
<img width="801" alt="Screen Shot 2022-10-20 at 8 24 49 PM" src="https://user-images.githubusercontent.com/18151143/197083723-33b91d3b-0db9-4c41-9d69-0217b35ecb7a.png">

**Comment by jmaslek** [comment]
appears throughout menu.  stoch is another example

**Comment by deeleeramone** [comment]
I have `legend location = best` in my custom style sheet. It works for most of the MPL charts.

![Screen Shot 2022-10-22 at 8 26 37 PM](https://user-images.githubusercontent.com/85772166/197371937-5c768c96-a8ac-4a5e-9899-fd31e556f9e4.png)

**Comment by jmaslek** [comment]
Yeah legend defaults to loc='best' on an axis.  Could play with legend sizing, but on this one, just the font size could also be reduced.  Some plots will likely just need more customizing than the generic style sheet.

**Comment by deeleeramone** [comment]
![Screen Shot 2022-10-22 at 8 37 31 PM](https://user-images.githubusercontent.com/85772166/197372267-ddd03c87-41f7-4d63-9cdc-f4da4a11c3c9.png)

**Comment by deeleeramone** [comment]
When the legend is hard-coded into the function, loc='best', doesn't get applied. 

![Screen Shot 2022-10-22 at 8 40 05 PM](https://user-images.githubusercontent.com/85772166/197372325-6867d235-e9d1-47da-ba96-c3f267a965cf.png)
![Screen Shot 2022-10-22 at 8 41 32 PM](https://user-images.githubusercontent.com/85772166/197372495-6a76d13a-44f1-4feb-8752-8850299eba93.png)

**Comment by jmaslek** [comment]
the economy ones are intentionally put outside the axes

**Comment by deeleeramone** [comment]
they should be full-width then, because the result is a shrinking chart canvas for every series that is included.
