### ISSUE TITLE
[Bug] ImportError

### ISSUE THREAD

**Issue by Kediel** [OpenBB-finance/OpenBB#6636]
**Describe the bug**
Can't import the openbb library due to the following message (see screenshot).

**To Reproduce**
Install with pip or pip3, start python, try to import library. Following instructions from documentation. 

**Screenshots**
<img width="823" alt="Screenshot 2024-08-21 at 16 10 55" src="https://github.com/user-attachments/assets/0cf78caa-f6f0-459a-990c-cf1c6a18ba01">

**Desktop (please complete the following information):**

- OS: Mac Sonoma 14.6.1
- Python version 3.11.6

**Additional context**
First time i'm trying so I'm not sure if older versions worked.

**Comment by deeleeramone** [comment]
Hi there, this is an environment error and not a bug.

You have installed this to your base Anaconda environment, which has resulted in incorrect versions and PATH links to important packages like Pydantic and anyio. 

Always create new environments for installing projects and check that your $PATH is correctly targeting the right Python environment.

**Comment by Kediel** [comment]
<img width="504" alt="Screenshot 2024-08-22 at 15 36 25" src="https://github.com/user-attachments/assets/8447fe9a-97ba-4c80-9cda-cf326fa95b75">
 Still experiencing an issue even in an isolate ENV.

**Comment by deeleeramone** [comment]
This is not a bug, otherwise nothing would work at all for anyone.

This will display all "openbb" packages installed in your environment: `pip list | grep openbb`

If it shows as being installed, then you have a local configuration in your shell profile that is erasing your PATH.

**Comment by Kediel** [comment]
Yes, i'm an idiot (Haven't used environments in a long time.). Disregard and thanks for the support!
