### ISSUE TITLE
[Bug] Missing HTTP Proxy Setting

### ISSUE THREAD

**Issue by MovisLi** [OpenBB-finance/OpenBB#6638]
**Describe the bug**
I notice the document metioned [Proxy Network in User Settings & Enviroment Variables](https://docs.openbb.co/platform/user_guides/settings_and_environment_variables#proxy-networks), but I can't find this setting in source codes anywhere. So is there some thing wrong in the document or the codes?

**To Reproduce**
1. Refer to other enviroment variables, I think `HTTP_PROXY` or `HTTPS_PROXY` should found in `openbb_core/env.py`. However it isn't.
2. Then I check the session definition file `openbb_core/utils/client.py`, there is a class named `ClientSession`, but it don't use `proxies` parameter durning initialization.
3. Then I check the request tool function `amake_request`, `make_request` in file `openbb_core/provider/utils/helpers.py`, it also doesn't use `proxies` parameter.

So, is `HTTP_PROXY` and `HTTPS_PROXY` deprecated?

**Screenshots**

Document
![image](https://github.com/user-attachments/assets/4f65d849-e0a7-42f8-8c7f-c912e6ac3690)

`openbb_core/env.py` File
![image](https://github.com/user-attachments/assets/a414c54f-2d36-48bd-8312-a011a5d5876f)

`openbb_core/utils/client.py`
![image](https://github.com/user-attachments/assets/aa62d53d-4a14-4313-aed0-5cffda56645f)

`openbb_core/provider/utils/helpers.py`
![image](https://github.com/user-attachments/assets/3ee77d16-e262-4859-85fe-68a01f914409)

**Desktop (please complete the following information):**

- OS: Windows 11
- Python version 3.11.9

**Additional context**
Thanks for answering my problem.

**Comment by deeleeramone** [comment]
Hi,

Thanks for the report. The issue arises from using both `requests` and `aiohttp`, and only `requests` reads the environment variables by default. I have added the necessary setting in the aiohttp.ClientSession initialization (#6640) to allow for the same behavior from all three HTTP IO helper functions - `make_request`, `amake_request`, and `amake_requests` - which should cover all HTTP requests throughout the library. 

Note that the vast majority of requests will be HTTPS and not HTTP, but for full coverage define both addresses.

See:  https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies
