### ISSUE TITLE
[Bug]: `tomlkit` not provided with Poetry's official isolated installer

### ISSUE THREAD

**Issue by dijonkitchen** [OpenBB-finance/OpenBB#6655]
**Describe the bug**
`tomlkit` not provided with Poetry's official isolated installer

Change was made in #6424

**To Reproduce**
1. Install Poetry: https://python-poetry.org/docs/#installing-with-the-official-installer
2. 
```sh
python dev_install.py
Traceback (most recent call last):
  File "/Users/jc/code/OpenBB/openbb_platform/dev_install.py", line 9, in <module>
    from tomlkit import dumps, load, loads
ModuleNotFoundError: No module named 'tomlkit'
```

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: 14.6.1 (23G93)
- Python version: 3.12.5

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
Hi there,

Please install Poetry with `pip install poetry`.

Other variations, such as `conda install poetry` can lead to unexpected complications.

**Comment by dijonkitchen** [comment]
Looking into this, I actually installed it with `pipx` per poetry docs, but that doesn't work. 

Making a virtual environment, activating it, and then installing works.

**Comment by deeleeramone** [comment]
Those are the steps outlined, on the installation page of the documentation, for running the `dev_install.py` script.
