### ISSUE TITLE
[Bug] can't run docker image

### ISSUE THREAD

**Issue by rafaelfliu** [OpenBB-finance/OpenBB#6689]
**Describe the bug**
Pulled the docker image successfully, but unable to run a container off the image. 
Encountered the following error message:
```
The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested.
exec /usr/local/bin/uvicorn: exec format error
```

**To Reproduce**
1. `docker pull ghcr.io/openbb-finance/openbb-platform:latest`
2. `docker run --rm -p 8000:8000 ghcr.io/openbb-finance/openbb-platform`

**Screenshots**
N.A.

**Desktop (please complete the following information):**
- OS: Ubuntu
- Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1

**Additional context**
N.A.

**Comment by tebrizetayi** [comment]
It does not work for me either

**Comment by ash34** [comment]
Because the docker image has been created for an ARM architecture only. It would work on a raspberry pi but most of us are on X86/AMD64.

**Comment by SurvivaLlama** [comment]
any chance we can get a docker for X86?

**Comment by deeleeramone** [comment]
Alternatively, you can use the [Dockerfile](https://github.com/OpenBB-finance/OpenBB/blob/develop/build/docker/platformAPI.Dockerfile) and spec it to your specific needs.

**Comment by asfourco** [comment]
@deeleeramone, not sure this should be classified as a bug unless the CI/CD tools are meant to deploy multi-arch docker images.

The manual steps to build would be:

1. Clone the repo
2. Assuming you have docker setup on your machine, rebuild for your machine using the command: `docker build -f build/docker/platform.dockerfile -t openbb-platform:latest .` Make sure to run this from the root of the OpenBB project

N.B. if you get the message that `http://deb.debian.org` cannot resolve, then modify the build command by adding the following flag `--network=host`, i.e., 
`docker build -f build/docker/platform.dockerfile -t openbb-platform:latest --network=host .`

**Comment by deeleeramone** [comment]
Closing this because the instructions referencing the container registry has been removed, please use the Dockerfile to build an image.
