### ISSUE TITLE
[🕹️ oss.gg] HACKTOBERFEST 2024

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBB#6705]
# OpenBB - Hacktoberfest 2024: Side Quests & Challenges

## ⭐ How to Get Started

Start by giving us a star:

[Star OpenBB on GitHub](https://github.com/openbb-finance/OpenBB)

## 📦 How to submit contributions

Follow the [instructions](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg) and open an issue [here](https://github.com/openbb-finance/OpenBB/issues/new/choose) for side quests and challenges.

### No-Code Side Quests

- 🎥 [Record your onboarding](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/0-set-upper.md) (🕹️ 150-300 Points)
- 🎬 [Create a YouTube Tutorial for Custom Copilot](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/1-pilot-copilot.md) (🕹️ 300 Points)
- ✍️ [Write a Use-Case Blog for OpenBB in Fundamental Analysis](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/2-fundamental-blog.md) (🕹️ 300 Points)
- 📝 [Post Your Investment Research on Reddit](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/3-reddit-legend.md) (🕹️ 150 Points)
- 📢 [Create a Social Media Post](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/4-social-poster.md) (🕹️ 50 Points)
- 📄 [Write an Article Comparing OpenBB and Other Financial Tools](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/5-financial-post.md) (🕹️ 300 Points)
- 🧵 [Publish a LinkedIn post or a Twitter Thread](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/no_code_side_quests/6-social-hero.md) (🕹️ 150-500 Points)

### Code Side Quests

- 🖥️ [Integrate OpenBB into a dashboard or web application](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/code_side_quests/1-openbb-integration.md) (🕹️ 300-750 Points)
- 🔧 [Create a custom backend for OpenBB Terminal](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/code_side_quests/2-custom-backend.md) (🕹️ 300-750 Points)
- 🤖 [Create a custom copilot for OpenBB Terminal](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/code_side_quests/3-custom-copilot.md) (🕹️ 300-750 Points)
- 🧠 [Create an AI Agent that utilizes OpenBB](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg/code_side_quests/4-agentic-agent.md) (🕹️ 300-750 Points)

## 🏆 Prize System

For every contribution you make (code or non-code), you earn points. Each point acts as a lottery ticket for the Hacktoberfest 2024 prize draw on October 31st. The more points you collect, the higher your chances of winning—but remember, even one point can win you a prize!

See 💬 FAQ at https://oss.gg/ 

## 📜 Rules & Best Practices

Assign yourself only if you’re ready to work on an issue.

Complete your tasks within the deadlines to avoid being unassigned.

Avoid spam or low-quality submissions—they will be disqualified.

Read all the guidelines carefully for each task or quest.

**Comment by kaif969** [comment]
![Screenshot 2024-10-18 010240](https://github.com/user-attachments/assets/fa315e7e-68a7-471a-aa2c-5a0e341bff1d)

**Comment by abhirajadhikary06** [comment]
@jmaslek Assign me a side quest of
 📢 Create a Social Media Post (🕹️ 50 Points)

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
