### ISSUE TITLE
[🕹️] Add Example Notebook Demonstrating Fundamental Analysis with OpenBB

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBB#6706]
# 📄 Task
  
Create a Jupyter notebook for our examples folder that demonstrates how to fetch financial KPIs and analyze valuations of public companies.

---

### 📋 Requirements:

1. **Template**: Start by copying the [example template notebook](https://github.com/OpenBB-finance/OpenBB/blob/develop/examples/COMMUNITY_EXAMPLE_TEMPLATE.ipynb).
3. **Content**: 
   - Give your notebook a meaningful name.
   - Fill in the details in the template, including the notebook title, description, your GitHub username, the notebook name in the Google Colab button, and any additional sections relevant to the task.
   - Write code that uses OpenBB's features to perform the analysis.
   - If your notebook requires additional dependencies, please specify those.
5. **Testing**: Ensure that all cells in the notebook run successfully and produce the intended results.
6. **Documentation**: Comment your code and to explain what each part does, and add markdown cells where necessary to provide explanations for the analysis.
7. **Output**: The final notebook should be added to the `examples` folder in this repository.

  
### 💡 Tips:

- You can refer to the [OpenBB Documentation](https://docs.openbb.co/) for additional guidance on using OpenBB features.
- If you encounter any issues, feel free to reach out for help in the discussions section or look at other example notebooks for inspiration.

### 📬 Submission:

- Follow the submission instructions detailed [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg)
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of your notebook and the analysis it performs in the PR body.
- Provide a working example of your notebook (e.g., screenshots of the output or a video demonstration) if possible.
  
---

Happy hacking!

**Comment by Manish-k723** [comment]
Hi @piiq @jmaslek @deeleeramone can some one please help me with a guide, what does here mean by fundamental analysis. 
What I understood is to do the basic stock analysis and I even found the same thing on google and from ChatGpt, I have raised two PR's but both of them got closed with comment as "This is not fundamental analysis". Pls help here, I really want to work on this and resolve it.

**Comment by piiq** [comment]
Hi @Manish-k723 
Your PRs were not accepted because they don't demonstrate performing fundamental analysis. Fundamental analysis focuses on assessing a company’s financial health and intrinsic value through metrics like revenue, earnings, assets, and market conditions.
To learn more about it I can suggest starting from https://www.investopedia.com/terms/f/fundamentalanalysis.asp

**Comment by SahiLmb** [comment]
#6927

**Comment by SahiLmb** [comment]
https://github.com/OpenBB-finance/OpenBB/pull/6927 #6927

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
