### ISSUE TITLE
[🕹️] Integrate DefiLlama's Public API with OpenBB Platform

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBB#6707]
# 📄 Task: (XXL: 1.500-3000 Points)

Integrate DefiLlama’s public API into the OpenBB Platform. Your task is to create a provider extension for DeFiLlama and implement the relevant commands in the `openbb-crypto` extension.

---

### 💡 Tips:

1. **Implementation**: Use the [DeliLlama API documentation](https://defillama.com/docs/api) to implement API calls for relevant data, such as DeFi metrics, protocols, and other valuable crypto data. No API key is required.
1. **Commands**: Integrate the new provider into the `openbb-crypto` extension by adding the necessary commands to fetch and display data from DeFiLlama.
1. **Testing**: Ensure all commands and API calls work as expected and handle edge cases (e.g., rate limits, missing data).
1. **Examples**: You can refer to existing implementations of extensions and providers [that have already been implemented repository](https://github.com/OpenBB-finance/OpenBB/tree/develop).

- Refer to the [OpenBB architecture overview](https://docs.openbb.co/platform/developer_guide/architecture_overview) for insight into the platform’s structure.
- Refer to the [OpenBB documentation](https://docs.openbb.co/platform/getting_started/create_new_provider_extension) to create a new provider extension for Defillama.
- Follow the instructions in the [mapping guide](https://docs.openbb.co/platform/getting_started/map_a_provider_to_a_route) to map the provider to the appropriate route within `openbb-crypto`.
- Check other examples of how provider extensions are implemented in the repo to guide your work.

### 📬 Submission:

- Follow the submission instructions [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg).
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of the integration and what commands were added in the PR body.
- Provide a working example of how to use the new provider extension (e.g., screenshots or video).

---

Happy hacking!

**Comment by the-praxs** [comment]
@piiq can I be assigned this since I already have a draft PR #6731 with a `/crypto/tvl/chains` command implemented and working?

<img width="812" alt="image" src="https://github.com/user-attachments/assets/f611bdb1-c758-4907-95b8-3b96a469cf18">

**Comment by aidoskanapyanov** [comment]
It should've unassigned me by now. Hi @the-praxs , you can have this issue since you already have a pr.

**Comment by the-praxs** [comment]
> It should've unassigned me by now. Hi @the-praxs , you can have this issue since you already have a pr.

Thanks! And good luck with the hacktoberfest 🚀

**Comment by aidoskanapyanov** [comment]
Thanks, good luck for you too @the-praxs ! 👍🏻

**Comment by the-praxs** [comment]
I am still working on it and will complete by weekend. My goal is to integrate all the defillama endpoints first then move to refactoring and tests.

**Comment by the-praxs** [comment]
Almost finished, issues are mentioned in the PR!

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
