### ISSUE TITLE
[🕹️] Create a Cryptocurrency Trend Analysis Notebook

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBB#6709]
## ⚠️ THIS IS A PART OF A LARGER QUEST. THIS ISSUE IS BLOCKED BY #6707 

# 📄 Task
 
Use OpenBB’s crypto data capabilities to build a notebook that analyzes trends in popular cryptocurrencies over time.

---

### 📋 Requirements:

1. **Template**: Start by copying the [example template notebook](https://github.com/OpenBB-finance/OpenBB/blob/develop/examples/COMMUNITY_EXAMPLE_TEMPLATE.ipynb).
2. **Content**: 
   - Give your notebook a meaningful name.
   - Fill in the details in the template, including the notebook title, description, your GitHub username, the notebook name in the Google Colab button, and any additional sections relevant to the task.
   - Write code that fetches and analyzes cryptocurrency data from OpenBB.
   - If your notebook requires additional dependencies, please specify those.
3. **Testing**: Ensure that all cells in the notebook run successfully and produce the intended results.
4. **Documentation**: Comment your code and add markdown cells where necessary to provide explanations for the analysis.
5. **Output**: The final notebook should be added to the `examples` folder in this repository.

### 💡 Tips:
  
- Refer to the [OpenBB Documentation](https://docs.openbb.co/) for guidance on using OpenBB features.

### 📬 Submission:

- Follow the submission instructions [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg).
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of your notebook and the analysis it performs in the PR body.

Happy hacking!

**Comment by theghostmac** [comment]
I believe I am done, and here is the link to my [PR](https://github.com/OpenBB-finance/OpenBB/pull/6728).

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
