### ISSUE TITLE
[🕹️] Design an Earnings Surprise Prediction Model in a Notebook

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBB#6719]
# 📄 Task
  
Provide an example of how to use OpenBB’s financial data to predict earnings surprises for companies.

---

### 📋 Requirements:

1. **Template**: Start by copying the [example template notebook](https://github.com/OpenBB-finance/OpenBB/blob/develop/examples/COMMUNITY_EXAMPLE_TEMPLATE.ipynb).
2. **Content**: 
   - Give your notebook a meaningful name.
   - Fill in the details in the template, including the notebook title, description, your GitHub username, the notebook name in the Google Colab button, and any additional sections relevant to the task.
   - Write code that uses OpenBB's features to model risk-return tradeoffs.
   - If your notebook requires additional dependencies, please specify those.
3. **Testing**: Ensure that all cells in the notebook run successfully and produce the intended results.
4. **Documentation**: Comment your code and add markdown cells where necessary to provide explanations for the analysis.
5. **Output**: The final notebook should be added to the `examples` folder in this repository.

### 💡 Tips:
  
- Refer to the [OpenBB Documentation](https://docs.openbb.co/) for guidance on using OpenBB features.

### 📬 Submission:

- Follow the submission instructions [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg).
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of your notebook and the analysis it performs in the PR body.

Happy hacking!

**Comment by mohitejaikumar** [comment]
@piiq I dont think someone is solving this issue , please assign it to me , I want to try this one

**Comment by bala-ceg** [comment]
@mohitejaikumar i am working on this

**Comment by piiq** [comment]
This issue is up for grabs

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
