### ISSUE TITLE
[🕹️] Create a Simple Sentiment Analysis for Stock Prices Notebook

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBB#6720]
# 📄 Task
  
Create a notebook that fetches sentiment data from financial news and correlates it with stock price movements.

---

### 📋 Requirements:

1. **Template**: Start by copying the [example template notebook](https://github.com/OpenBB-finance/OpenBB/blob/develop/examples/COMMUNITY_EXAMPLE_TEMPLATE.ipynb).
2. **Content**: 
   - Give your notebook a meaningful name.
   - Fill in the details in the template, including the notebook title, description, your GitHub username, the notebook name in the Google Colab button, and any additional sections relevant to the task.
   - Write code that uses OpenBB's features to model risk-return tradeoffs.
   - If your notebook requires additional dependencies, please specify those.
3. **Testing**: Ensure that all cells in the notebook run successfully and produce the intended results.
4. **Documentation**: Comment your code and add markdown cells where necessary to provide explanations for the analysis.
5. **Output**: The final notebook should be added to the `examples` folder in this repository.

### 💡 Tips:
  
- Refer to the [OpenBB Documentation](https://docs.openbb.co/) for guidance on using OpenBB features.

### 📬 Submission:

- Follow the submission instructions [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg).
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of your notebook and the analysis it performs in the PR body.

Happy hacking!

**Comment by Shaik-mohd-huzaifa** [comment]
I have done this project before assign this one for me?

**Comment by Harsh9485** [comment]
assign

**Comment by piiq** [comment]
This issue is up for grabs again

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
