### ISSUE TITLE
[Bug] Pricing page of Homepage is not showing CTA buttons

### ISSUE THREAD

**Issue by Hujaakbar** [OpenBB-finance/OpenBB#6746]
**Describe the bug**

On screens wider than 1024px , Pricing page of OpenBB homepage is not showing "Get Started" and "Contact Us" CTA buttons

**To Reproduce**
Visit the page in a desktop: https://www.openbb.co/pricing

**Screenshots**

working when screen is narrower than 1024px
![image](https://github.com/user-attachments/assets/eae2c671-f40a-4f95-b507-15c4f607e050)

Not working when screen is wider than 1024px

![image](https://github.com/user-attachments/assets/1c8cdc80-a8bc-416c-96a0-adb24f37afc4)

![image](https://github.com/user-attachments/assets/69ee6d9e-b3a1-48e0-a162-1a9ad0ba43f7)

![image](https://github.com/user-attachments/assets/70d480e9-bb2f-4dc2-9d1a-1ef98002d993)

**Desktop (please complete the following information):**

- OS: Fedora, 
- Browser: Chrome

**Additional context**

I wanted to submit a PR, but couldn't find homepage's source code in this repo. 

Fix is simple
From below two div containers, remove  this tailwind class: `md:h-[1000px]`

change this: 

```html

<div class="border border-website-700 p-4 shadow-dark-3 lg:p-8 relative flex flex-col overflow-hidden rounded-sm md:rounded-xl !p-px md:h-[1000px] max-w-[488px] bg-website-800">
...
</div>
<div class="border border-website-700 p-4 shadow-dark-3 lg:p-8 relative flex flex-col overflow-hidden rounded-sm md:rounded-xl !p-px md:h-[1000px] max-w-[488px] bg-website-800 before:absolute before:inset-0 before:rounded-lg before:p-0.5 before:bg-gradient-to-br before:from-light-blue-400 before:via-light-blue-900 before:to-transparent">
....
</div>

```

to this

```html
<div class="border border-website-700 p-4 shadow-dark-3 lg:p-8 relative flex flex-col overflow-hidden rounded-sm md:rounded-xl !p-px max-w-[488px] bg-website-800">
...
</div>
<div class="border border-website-700 p-4 shadow-dark-3 lg:p-8 relative flex flex-col overflow-hidden rounded-sm md:rounded-xl !p-px  max-w-[488px] bg-website-800 before:absolute before:inset-0 before:rounded-lg before:p-0.5 before:bg-gradient-to-br before:from-light-blue-400 before:via-light-blue-900 before:to-transparent">
....
</div>

```

**Result:**

![image](https://github.com/user-attachments/assets/e85523a7-6932-4cad-b2ef-ae289a512a63)

**Comment by jose-donato** [comment]
thank you for the detailed issue 🙌 i'll take care of it
