### ISSUE TITLE
[Bug] Vanilla docker and pip openbb "Unable to connect to URL."

### ISSUE THREAD

**Issue by zalo** [OpenBB-finance/OpenBB#6749]
**Describe the bug**
Installing `openbb` via dockerfile (Linux x64) or pip (Windows x64) yields a working FastAPI server (`/docs` works), but the `/` and `/widgets.json` endpoints are 404'd.
However the [OpenBB Platform Installer](https://my.openbb.co/app/platform/downloads) (Windows x64), appears to correctly expose ~370 widgets.

An example broken `openbb-platform` API server can be found here: ~~https://openbb.sels.tech/~~
- Note that ~~[/docs](https://openbb.sels.tech/docs)~~ is functional.

**To Reproduce**
- Use the built-in Dockerfile or `pip install openbb[all]` command on Windows.
- Run `python -c 'import openbb; openbb.build()'` to build the python assets(?)
- Attempt to add this new server as a custom backend.

**Screenshots**
![image](https://github.com/user-attachments/assets/8e8dd216-bb97-4c69-bc4f-c483701dc336)

**Desktop (please complete the following information):**

- OS: Windows 11 x64, Ubuntu 22.24 Jammy
- Python version 3.10, 3.10

**Additional context**
Question: Are the installer `openbb-platform` and the `pip openbb-platform` meant to be different?  If so, is there a process to make them match up?

**Comment by deeleeramone** [comment]
Hi there,

When you call `uvicorn openbb.api.rest_api:app`, you do not get the widgets builder script.

For Linux, try:

```
pip install openbb-platform-api

openbb-api
```

**Comment by jmaslek** [comment]
Alternatively this will work for a dockerfile

```
FROM python:3.10-slim-bookworm

WORKDIR /app

RUN pip install "openbb[all]"

RUN pip install openbb-platform-api

ENTRYPOINT ["openbb-api", "--host", "0.0.0.0"]
```

Just make sure to map the port

**Comment by zalo** [comment]
Ah that was it; I feel silly now... where was it in the documentation?

Thank you!

**Comment by o6uoq** [comment]
> Ah that was it; I feel silly now... where was it in the documentation?

It's not, but it should be.
