### ISSUE TITLE
Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by antilpiyush89** [OpenBB-finance/OpenBB#6778]
### What side quest or challenge are you solving?

Get 5 people to star our repository

### Points

150 points

### Provide proof that you've completed the task

![IMG-20241015-WA0002](https://github.com/user-attachments/assets/f6bbd793-136c-4baf-8b22-b3ca97d1b218)
![IMG-20241015-WA0003](https://github.com/user-attachments/assets/dde9eb69-c189-43d8-966c-009078e08612)
![IMG-20241014-WA0024](https://github.com/user-attachments/assets/32815a78-bc31-4200-8ac5-6f794efd4851)
![IMG-20241015-WA0009](https://github.com/user-attachments/assets/17981916-bbfe-4697-b891-5f103ac03cf7)
![IMG-20241015-WA0010(1)](https://github.com/user-attachments/assets/129de0b7-7d29-4d5a-b287-707431fb0cc9)

**Comment by newcomer119** [comment]
What side quest or challenge are you solving?
Get 5 people to star our repository

Points
150 points

Description
No response

Provide proof that you've completed the task : 

![g1](https://github.com/user-attachments/assets/fbf61735-520b-44fd-a4de-0d28d7b99afb)
![g5](https://github.com/user-attachments/assets/9333ca59-4945-4038-8067-5a917c598073)
![g3](https://github.com/user-attachments/assets/6f1affc5-0166-48f5-a850-5245b64d8cf6)
![g4](https://github.com/user-attachments/assets/a601ea46-97d2-4c93-8152-dfd411504d0d)
![g2](https://github.com/user-attachments/assets/007f614b-bf89-403c-a08e-a5f1876402dc)

**Comment by newcomer119** [comment]
What side quest or challenge are you solving?
Get 5 people to star our repository

Points
150 points

Description
No response

Provide proof that you've completed the task

![g2](https://github.com/user-attachments/assets/aeb21915-c6fb-43a3-a4aa-943248ffd19d)
![g1](https://github.com/user-attachments/assets/82250424-4fac-4903-94ce-28a7315bdc16)
![g5](https://github.com/user-attachments/assets/18e487fc-078b-44a7-901f-258767819172)
![g4](https://github.com/user-attachments/assets/9d80e34c-a77b-45f7-abe9-2a7feb3311d1)
![g3](https://github.com/user-attachments/assets/7f80d295-f541-410e-96ca-2e60885c79b7)

**Comment by newcomer119** [comment]
> /award 150

i have also completed the task
