### ISSUE TITLE
[Bug] tiingo and biztoc providers for world news in SDK and openbb-cli not working

### ISSUE THREAD

**Issue by tatsean-dhumall** [OpenBB-finance/OpenBB#6784]
**Describe the bug**
Either using SDK or openbb-cli, it throws the same error when trying to access world news. 

**To Reproduce**
Run the following command in openbb cli
world --provider biztoc
world --provider tiingo

if we are using the SDK, can try with this, as it throws the same errors too: 
from openbb import obb
obb.news.world(provider='biztoc')
obb.news.world(provider='tiingo', source='yahoo')

**Screenshots**
![image (2)](https://github.com/user-attachments/assets/dcbf592e-ec0f-40c7-a7a4-510f1cd07655)
![image (1)](https://github.com/user-attachments/assets/7500653d-c05a-4dc1-aa5c-3521bb3e14cb)
![image](https://github.com/user-attachments/assets/b5273fbd-993b-4eeb-8c61-60d77785f1f2)

**Desktop (please complete the following information):**
- OS : Windows 11
- Python version: 3.12.2

**Comment by BadriVishalPadhy** [comment]
@pchaganti can u assign this issue to me

**Comment by deeleeramone** [comment]
Hi there, this is resolved by #6800
