### ISSUE TITLE
[🕹️] Completed Side Quest:  5 Friends Starred Repositories

### ISSUE THREAD

**Issue by chrahman** [OpenBB-finance/OpenBB#6790]
### What side quest or challenge are you solving?

1050 Points 🔥 Get 5 friends to star our repos

### Points

150

### Description

I have completed the side quest by having 5 of my friends star the required repositories. Below are the screenshots from their GitHub profiles as proof.

### Provide proof that you've completed the task

![5](https://github.com/user-attachments/assets/ceac56d9-9b2a-4dca-804d-645276460732)
![4](https://github.com/user-attachments/assets/ccf19543-a597-4f4f-a10b-6ae40d1632ff)
![1](https://github.com/user-attachments/assets/77dd90a2-6442-4c3e-a987-2a425b0879f3)
![2](https://github.com/user-attachments/assets/3e2bb0ad-8cde-4a8d-9966-0bb7ca8d1546)
![3](https://github.com/user-attachments/assets/fd621778-09fa-47bc-8b08-4960ef0bbf5f)

**Comment by thefool76** [comment]
> ### What side quest or challenge are you solving?
> 1050 Points 🔥 Get 5 friends to star our repos
> 
> ### Points
> 750
> 
> ### Description
> I have completed the side quest by having 5 of my friends star the required repositories. Below are the screenshots from their GitHub profiles as proof.
> 
> ### Provide proof that you've completed the task
> ![5](https://private-user-images.githubusercontent.com/68278872/377041935-ceac56d9-9b2a-4dca-804d-645276460732.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM0NDUsIm5iZiI6MTcyOTA5MzE0NSwicGF0aCI6Ii82ODI3ODg3Mi8zNzcwNDE5MzUtY2VhYzU2ZDktOWIyYS00ZGNhLTgwNGQtNjQ1Mjc2NDYwNzMyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTM5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2FkYjEyZTYwN2M5ZTA3NjQ4MzViMjM0YTQ5NDYxOWMwYmQwZDM5ODNiNTAxZmMxNzZiZDZlYzAzNTc1Y2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RokPdHVxrU8yTuYaL8fvgv5eifgvxfjEMnRGVStRI7Q) ![4](https://private-user-images.githubusercontent.com/68278872/377041975-ccf19543-a597-4f4f-a10b-6ae40d1632ff.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM0NDUsIm5iZiI6MTcyOTA5MzE0NSwicGF0aCI6Ii82ODI3ODg3Mi8zNzcwNDE5NzUtY2NmMTk1NDMtYTU5Ny00ZjRmLWExMGItNmFlNDBkMTYzMmZmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTM5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDI1NjQ5NGQwODM0ZmFlZDU2ZjAxNzFjYWY3ZjQ3YTNkYTQ4NWI4NDY2MjIxM2Q2ZjhmMzAzMzFmZmZiMzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Al7rmZ8J1TjG_5rSzEJi4SJZrCZ2kibBSpQq3ZVGSC0) ![1](https://private-user-images.githubusercontent.com/68278872/377041768-77dd90a2-6442-4c3e-a987-2a425b0879f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM0NDUsIm5iZiI6MTcyOTA5MzE0NSwicGF0aCI6Ii82ODI3ODg3Mi8zNzcwNDE3NjgtNzdkZDkwYTItNjQ0Mi00YzNlLWE5ODctMmE0MjViMDg3OWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE1MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1M2Y3NzNkNDgyZTVhNDU4ZDNlZDdlNTlmOGU3ZjlhNmY1ZDMyZDU1ODJiZTE3OTY4NTUzMTZkZmVlZGZjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QqvOct_B1w5ddOz8igqkiVEbhmQwOrzzJhN-JTd8Efc) ![2](https://private-user-images.githubusercontent.com/68278872/377041876-3e2bb0ad-8cde-4a8d-9966-0bb7ca8d1546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM0NDUsIm5iZiI6MTcyOTA5MzE0NSwicGF0aCI6Ii82ODI3ODg3Mi8zNzcwNDE4NzYtM2UyYmIwYWQtOGNkZS00YThkLTk5NjYtMGJiN2NhOGQxNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE1MzkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3N2IzNGM3Y2YyZDU3OTA4MTU5YmUxODA0NWUyYWZhZmM3YjVhNzkzOTNmOWYyZWZjZmY1MzhhZDA0ZWE0NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jmOwyzg-XxBsVnaJtGUcOGWd1kHu-i3OilijQ2xToBY) ![3](https://private-user-images.githubusercontent.com/68278872/377041905-fd621778-09fa-47bc-8b08-4960ef0bbf5f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTM0NDUsIm5iZiI6MTcyOTA5MzE0NSwicGF0aCI6Ii82ODI3ODg3Mi8zNzcwNDE5MDUtZmQ2MjE3NzgtMDlmYS00N2JjLThiMDgtNDk2MGVmMGJiZjVmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNTM5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDBjOTNlZTRlOTRkYzk3OTA2NGU5M2QyMDhlYzQzNmM2MjNkNTEyYzEwN2Q0NmMwM2QwNTE1Y2FkYTM4NzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OvRprpKPdhKyznKVH3Y4UDmMbIju4eEHD5u5Cv4S9KU)

Small Correction -  I think it's 150 points per repo right so 7 repo = 1050
could you please change it to 150 rather than 750
