### ISSUE TITLE
[🕹️] [Bug] LinkedIn logo is not visible in dark mode 

### ISSUE THREAD

**Issue by deepikaa0402** [OpenBB-finance/OpenBB#6805]
### What side quest or challenge are you solving?

While navigating the website in dark mode, I noticed that the LinkedIn logo was blending into the background, making it difficult to distinguish. 

### Points

50 points

### Description

During a review of the website's UI in dark mode, I identified a significant issue regarding the visibility of the LinkedIn logo. The logo was not clearly distinguishable against the dark background, which could hinder user recognition and brand visibility. To further assess the problem, I utilized accessibility tools to evaluate the contrast ratio of the logo against the background.

### Provide proof that you've completed the task

This is how the logo looks like when in white mode.
![Screenshot 2024-10-15 213743](https://github.com/user-attachments/assets/ae7585a7-f367-4d29-9776-92eb3aa3515b)

 And this is how it is not distinguishable in dark mode.
![Screenshot 2024-10-15 213812](https://github.com/user-attachments/assets/fd13e673-eafd-4c8e-a1b8-b27403a6c5ff)

**Comment by prankurpandeyy** [comment]
please assign this to me

**Comment by deeleeramone** [comment]
Hi, what do the supplied screenshots have to do with OpenBB and its website?

![Screenshot 2024-10-18 at 11 07 41 AM](https://github.com/user-attachments/assets/f14689f3-bd5b-45e4-8063-4b19a424e3c1)

**Comment by deeleeramone** [comment]
Seemingly the wrong repository.
