### ISSUE TITLE
[🕹️] Side Quest: Write a Use-Case Blog for OpenBB in Fundamental Analysis

### ISSUE THREAD

**Issue by sahiladit** [OpenBB-finance/OpenBB#6806]
### What side quest or challenge are you solving?

Create a detailed blog post showcasing how OpenBB can be used for fundamental analysis in stock markets

### Points

300 Points

### Description

Link:https://medium.com/@sahiladit/unlocking-the-power-of-openbb-for-fundamental-analysis-a-comprehensive-use-case-5475cc7dc4ea

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-19 at 12 28 25 AM" src="https://github.com/user-attachments/assets/1d9d8ad9-1b67-4aaf-8a99-d4457b42e20f">

**Comment by Ibukun-tech** [comment]
Can I be assigned this

**Comment by Ibukun-tech** [comment]
I will write a detailed blog post how OpenBB can be used for fundamental analysis in stock markets
