### ISSUE TITLE
[🕹️]Side Quest: Publish a LinkedIn post or a Twitter Thread on OpenBB’s Use in Investment Research

### ISSUE THREAD

**Issue by Naprila** [OpenBB-finance/OpenBB#6822]
### What side quest or challenge are you solving?

Publish a LinkedIn post or a Twitter Thread on OpenBB’s Use in Investment Research

### Points

150-500 Points

### Description

Published a X post on OpenBB’s Use in Investment Research

Link: https://x.com/mkprasad_821/status/1847707536562028901

### Provide proof that you've completed the task

<img width="1369" alt="Screenshot 2024-10-20 at 12 32 34 AM" src="https://github.com/user-attachments/assets/14d213a2-a000-44fb-aade-63f23d7d3b49">

**Comment by ajydeep** [comment]
@Naprila I've created a thread. What am I supposed to do next, like do I have to create a PR?

**Comment by ajydeep** [comment]
@Naprila I've published a twitter thread.
![image](https://github.com/user-attachments/assets/bb3f75ca-c4b8-4ede-88e0-177d977a6956)
