### ISSUE TITLE
[🕹️] Follow on X

### ISSUE THREAD

**Issue by sateshcharan** [OpenBB-finance/OpenBB#6825]
### What side quest or challenge are you solving?

Follow on X

### Points

50

### Description

Follow on X

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/68e50b88-274a-4321-877d-4ecf2643d63b)

**Comment by ADP-1** [comment]
#6825
### I followed OpenBB on x 

**Here is the proof**
![Screenshot 2024-10-21 130815](https://github.com/user-attachments/assets/596265b7-a463-47d9-8e58-29e1e3457b10)
