### ISSUE TITLE
[🕹️] No-Code Side Quests Twitter thread 

### ISSUE THREAD

**Issue by PalashCoder** [OpenBB-finance/OpenBB#6849]
### What side quest or challenge are you solving?

I have published one twitter thread.

### Points

(🕹️ 150-500 Points )

### Provide proof that you've completed the task

Here is the link of the threadd:- [Link ](https://x.com/coderpalash/status/1849070684003057794)

**Comment by SNIDGHA** [comment]
What side quest or challenge are you solving?
I'm tackling the No-Code Side Quest for OpenBB Finance! My challenge is to create engaging Twitter threads to spread the word about this amazing AI-powered financial research tool. Helping to grow awareness and build a community around #OpenBB while making finance accessible for all. 🌍💡

Points
150-500 Points

Description
I contributed to the No-Code Side Quest for OpenBB Finance by crafting engaging Twitter content to raise awareness about the platform. My task involved creating tweets and threads that highlight OpenBB’s AI-powered research and analytics tools, promoting its features, and encouraging community involvement. This helps make financial tools more accessible and educates users about the power of open-source finance.

Provide proof that you've completed the task
Here's the link to the tweet(s) showcasing my contribution: https://x.com/snigdha_1234567/status/1849315580719063113
https://x.com/snigdha_1234567/status/1849315583067873290

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
