### ISSUE TITLE
[🕹️] Starry-eyed supporter 

### ISSUE THREAD

**Issue by PratikAwaik** [OpenBB-finance/OpenBB#6851]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/f53b8008-934e-4102-8d4f-48c7a8f61ed6)
![image](https://github.com/user-attachments/assets/75d94880-07e6-41d0-b693-997497a2f4d2)
![image](https://github.com/user-attachments/assets/256b9f44-f1fb-4dfb-86f3-05b27ae6b882)
![image](https://github.com/user-attachments/assets/592467c9-ccf0-4f38-9160-a80c741b8c82)
![image](https://github.com/user-attachments/assets/4fec81fb-5038-4c71-b757-a664b276a548)

**Comment by Dharmil20** [comment]
@PratikAwaik Can You Please Explain more about the issue?

**Comment by PratikAwaik** [comment]
@Dharmil20 its not an issue, its a side quest submission!
