### ISSUE TITLE
[🕹️] Side Quest: Integrate OpenBB into a dashboard

### ISSUE THREAD

**Issue by soamn** [OpenBB-finance/OpenBB#6867]
### What side quest or challenge are you solving?

Side Quest: Integrate OpenBB into a dashboard or web application

### Points

Points: 300-750 Points

### Provide proof that you've completed the task

[https://github.com/soamn/oss-obb-dashboard](url)

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
