### ISSUE TITLE
[🕹️]Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by sumit2011** [OpenBB-finance/OpenBB#6918]
### What side quest or challenge are you solving?

star the repo

### Points

150 Points

### Description

stared the OpenBB repo

### Provide proof that you've completed the task

![1](https://github.com/user-attachments/assets/71cbff0d-e0c6-4646-a711-1a915b73eb2d)
![2](https://github.com/user-attachments/assets/069e9614-3625-40a0-b66f-bec7a0d03b3e)
![3](https://github.com/user-attachments/assets/006a0cef-f755-45eb-b42e-a9f748f57978)
![4](https://github.com/user-attachments/assets/eb7f78d5-3604-4242-ba2a-9721357ed89c)
![5](https://github.com/user-attachments/assets/6d62aed4-405b-4620-966f-48260e9482c4)

**Comment by Shrinivasdumbali** [comment]
![1](https://github.com/user-attachments/assets/274fb93a-1da7-4bfc-a6d9-ab432fe335ee)
![2](https://github.com/user-attachments/assets/b3d6567e-9cc0-4549-b09b-2e504c8d722c)
![3](https://github.com/user-attachments/assets/1a0f02ee-a3f4-4ca5-aa3a-303dd627e74c)
![4](https://github.com/user-attachments/assets/70bf1c4c-724a-49b3-8d52-1d33ce4a5392)
![5](https://github.com/user-attachments/assets/41a38749-d476-45fd-8845-dfa73216ed15)

side query completed!
