### ISSUE TITLE
[🕹️] Publish a LinkedIn post or a Twitter Thread on OpenBB’s Use in Investment Research

### ISSUE THREAD

**Issue by thefool76** [OpenBB-finance/OpenBB#6920]
### What side quest or challenge are you solving?

Publish a LinkedIn post or a Twitter Thread on OpenBB’s Use in Investment Research

### Points

150-500 Points

### Provide proof that you've completed the task

I apologise for the inconvenience below I have added the link to my X thread 🧵 I have added a detailed use case of openBB

[Click here](https://x.com/thefool1135/status/1851821631619977725?s=19)

**Comment by thefool76** [comment]
@jmaslek can you please review this ? Thank you

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
