### ISSUE TITLE
[🕹️] [oss.gg hackathon] Starry-eyed supporter

### ISSUE THREAD

**Issue by Shrinivasdumbali** [OpenBB-finance/OpenBB#6921]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Description

Got five friends to star OpenBB repository.

### Provide proof that you've completed the task

![1](https://github.com/user-attachments/assets/5325e42f-6bac-47b4-82e2-639bff85ea8e)
![2](https://github.com/user-attachments/assets/118cee9d-272a-47b5-9fea-8b61c49fad4a)
![3](https://github.com/user-attachments/assets/4e56376c-c5a2-45b2-bddf-210eb89763b3)
![4](https://github.com/user-attachments/assets/30a056e8-870c-446b-8999-2cf3c8fed5cd)
![5](https://github.com/user-attachments/assets/86ad716b-654b-46c6-905a-cb8b862922cd)

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
