### ISSUE TITLE
[🕹️] Star eyed supporter

### ISSUE THREAD

**Issue by Dehelaan** [OpenBB-finance/OpenBB#6923]
### What side quest or challenge are you solving?

Get five friends to star

### Points

150

### Provide proof that you've completed the task

![Screenshot 2024-10-26 211440](https://github.com/user-attachments/assets/7381bbaa-85a4-4868-bc01-6b8eacaa3379)
![Screenshot 2024-10-26 211634](https://github.com/user-attachments/assets/68a2c524-6eff-4c14-adbf-2e0e95588c56)
![Screenshot 2024-10-26 214922](https://github.com/user-attachments/assets/103a7dd2-5fe7-40b7-af5d-2ad16d9a23ee)
![Screenshot 2024-10-26 215706](https://github.com/user-attachments/assets/de220852-10ec-461b-8cf3-2d4b7962f8c6)
![WhatsApp Image 2024-10-26 at 21 09 25_6f92659b](https://github.com/user-attachments/assets/94f05dcf-511f-416a-8022-fd20f8f9e551)

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
