### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by Nabhag8848** [OpenBB-finance/OpenBB#6924]
### What side quest or challenge are you solving?

asked five of my friends to star the repository

### Points

150

### Provide proof that you've completed the task

1. https://github.com/amannegi?tab=stars
![Aman](https://github.com/user-attachments/assets/4f7d3586-528e-439b-9520-f1395d21b88b)

2. https://github.com/DhairyaMajmudar?tab=stars
![Dhairya](https://github.com/user-attachments/assets/c469f3c7-9411-47d5-a0b0-dd282520f344)

3. https://github.com/kunal00000?tab=stars
![Kunal](https://github.com/user-attachments/assets/354aeddb-02b7-4029-90ee-444afd44a805)

4. https://github.com/narharim?tab=stars
![Narhari](https://github.com/user-attachments/assets/b2a10225-f997-4209-b83e-6fe3e3a259ae)

5. https://github.com/VipinDevelops?tab=stars
![Vipin](https://github.com/user-attachments/assets/1ff878b5-271b-4c66-9ab0-4e13bdeeef5f)

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks
