### ISSUE TITLE
[Bug] Getting a HTTPS error pointing to us.i.posthog.com when running the basic getting started code

### ISSUE THREAD

**Issue by seantanjx** [OpenBB-finance/OpenBB#6926]
**Describe the bug**
When following the getting started guide, I ran the basic code to get historical data of AAPL, I got this error message: `error uploading: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b6d04bacb50>: Failed to establish a new connection: [Errno 111] Connection refused'))`

However, i still managed to get the data of the AAPL ticker. It is just annoying to constantly see that error and it is taking a long time to run - not sure what is causing this.

I am seeing:
{above error}
{results}
{above error"

So the error message poped up twice.

**To Reproduce**
1. Create python env and activate it
2. Run `pip install 'openbb[all]'`
3. Add the following lines to a python file:
`from openbb import obb`
`output = obb.equity.price.historical("AAPL")`
`df = output.to_dataframe()`
`df.head()`

4. Run the python file
Output:

`error uploading: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5787b3c490>: Failed to establish a new connection: [Errno 111] Connection refused'))`

`            open  high   low  close      volume
date                                           
2004-01-02  0.39  0.39  0.38   0.38  2024993600
2004-01-05  0.38  0.40  0.38   0.40  5530257600
2004-01-06  0.40  0.40  0.39   0.40  7130872000
2004-01-07  0.40  0.41  0.39   0.41  8216241600
2004-01-08  0.41  0.42  0.41   0.42  6444244800`

`error uploading: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5787b604d0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Desktop (please complete the following information):**

- OS: Pop!_OS 22.04 LTS
- Python version: 3.11.5

**Comment by deeleeramone** [comment]
Hi there,

What kind of machine is this, a virtual machine or a desktop? Are you connected to the internet via VPN or other kind of proxy?
