### ISSUE TITLE
[Bug] API docs can't show out the right parameters

### ISSUE THREAD

**Issue by joshuaBri** [OpenBB-finance/OpenBB#6938]
**Describe the bug**
the api docs which i generated can't show out the right query parammeters

**To Reproduce**
just type the command below: 
uvicorn openbb_core.api.rest_api:app --host 0.0.0.0 --port 8000 --reload

**Screenshots**
![Snipaste_2024-11-07_15-46-43](https://github.com/user-attachments/assets/48510b02-082f-405d-b466-0e7c4fa9a35b)

**Desktop (please complete the following information):**
- windows: 10
- Python version [e.g. 3.11.10]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
There are some technical limitations within the Swagger UI, enums do not concatenate across all providers. However, it still works. The only alternative would be to make it a pure string entry and not have enums. They are supposed to be more "helpful", but maybe this isn't always desirable.

<img width="980" alt="Screenshot 2024-11-07 at 8 59 42 AM" src="https://github.com/user-attachments/assets/221d92c6-3264-41c4-a2a6-2853583ebd88">

**Comment by deeleeramone** [comment]
Closing this as it is a Swagger UI limitation, feel free to reopen if you encounter operational bugs in actual use.
