### ISSUE TITLE
[Bug] limit parameter not working

### ISSUE THREAD

**Issue by saad-sahir** [OpenBB-finance/OpenBB#6954]
I ran this code from the Getting Started documentation but the limit parameter doesn't return the n number of rows. It always defaults to 5. I haven't found a solution to the problem yet anywhere else so I'm adding this here.

(
    obb.equity.fundamental.income(
        "TGT", 
        provider="yfinance",
        limit=10,
        period="quarter"
    ).to_df()
)

I am running this on openbb 4.3.4 in python 3.12

**Comment by deeleeramone** [comment]
Hi, the limit parameter does not apply to yFinance, there are no query controls and only returns the last five periods.
