### ISSUE TITLE
[Bug] No matching distribution found for openbb-us-eia==1.0.0b

### ISSUE THREAD

**Issue by joshuaBri** [OpenBB-finance/OpenBB#6965]
**Describe the bug**
![image](https://github.com/user-attachments/assets/8ead6439-b7d5-4101-88a0-d3b462c289f1)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement openbb-us-eia==1.0.0b (from versions: none)
ERROR: No matching distribution found for openbb-us-eia==1.0.0b

**To Reproduce**
pip install openbb-us-eia==1.0.0b

**Comment by deeleeramone** [comment]
Yes, this extension only lives on the develop branch, it has not been published to PyPI. You can install locally with the `dev_install.py` script.

**Comment by deeleeramone** [comment]
Closing because issue is resolved by #6966
