### ISSUE TITLE
[Bug] Passing One Symbol to `price.historical` reuslts in Unexpected Error

### ISSUE THREAD

**Issue by jjfantini** [OpenBB-finance/OpenBB#6975]
**Describe the bug**
Every time that I make a query with just one symbol, I get an uninformative error saying `Unexpected Error Occurred.` I am using poetry to manage installations and conda for environments, and done a fresh install of openbb but I am still getting the same error.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
```py
# WORKS
obb.equity.price.historical(
symbol="AAPL,PCT"
start_date=self.context_params.start_date,
end_date=self.context_params.end_date,
provider=self.context_params.provider,
adjustment="splits_and_dividends",
)
```

```py
# DOESNT WORK
obb.equity.price.historical(
symbol="AAPL"
start_date=self.context_params.start_date,
end_date=self.context_params.end_date,
provider=self.context_params.provider,
adjustment="splits_and_dividends",
)
```

ERROR
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/menv/lib/python3.12/site-packages/openbb_core/app/static/utils/decorators.py", line 90, in wrapper
    raise OpenBBError("\n[Error] -> Unexpected error.").with_traceback(
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/menv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
openbb_core.app.model.abstract.error.OpenBBError: 
[Error] -> Unexpected error.
```

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: Latest Mac OS
- Python version [e.g. 3.12.6]

**Additional context**
 name         : openbb                                      
 version      : 4.3.3                                       
 description  : Investment research for everyone, anywhere. 

dependencies
 - openbb-alpha-vantage >=1.3.3,<2.0.0
 - openbb-benzinga >=1.3.3,<2.0.0
 - openbb-biztoc >=1.3.3,<2.0.0
 - openbb-bls >=1.0.1,<2.0.0
 - openbb-cboe >=1.3.3,<2.0.0
 - openbb-cftc >=1.0.1,<2.0.0
 - openbb-charting >=2.2.3,<3.0.0
 - openbb-commodity >=1.2.3,<2.0.0
 - openbb-core >=1.3.3,<2.0.0
 - openbb-crypto >=1.3.3,<2.0.0
 - openbb-currency >=1.3.3,<2.0.0
 - openbb-derivatives >=1.3.3,<2.0.0
 - openbb-ecb >=1.3.3,<2.0.0
 - openbb-econdb >=1.2.3,<2.0.0
 - openbb-econometrics >=1.4.3,<2.0.0
 - openbb-economy >=1.3.3,<2.0.0
 - openbb-equity >=1.3.3,<2.0.0
 - openbb-etf >=1.3.3,<2.0.0
 - openbb-federal-reserve >=1.3.3,<2.0.0
 - openbb-finra >=1.3.3,<2.0.0
 - openbb-finviz >=1.2.3,<2.0.0
 - openbb-fixedincome >=1.3.3,<2.0.0
 - openbb-fmp >=1.3.3,<2.0.0
 - openbb-fred >=1.3.3,<2.0.0
 - openbb-government-us >=1.3.3,<2.0.0
 - openbb-imf >=1.0.0,<2.0.0
 - openbb-index >=1.3.3,<2.0.0
 - openbb-intrinio >=1.3.3,<2.0.0
 - openbb-multpl >=1.0.3,<2.0.0
 - openbb-nasdaq >=1.3.3,<2.0.0
 - openbb-news >=1.3.3,<2.0.0
 - openbb-oecd >=1.3.3,<2.0.0
 - openbb-polygon >=1.3.3,<2.0.0
 - openbb-quantitative >=1.3.3,<2.0.0
 - openbb-regulators >=1.3.3,<2.0.0
 - openbb-sec >=1.3.3,<2.0.0
 - openbb-seeking-alpha >=1.3.3,<2.0.0
 - openbb-stockgrid >=1.3.3,<2.0.0
 - openbb-technical >=1.3.3,<2.0.0
 - openbb-tiingo >=1.3.3,<2.0.0
 - openbb-tmx >=1.2.3,<2.0.0
 - openbb-tradier >=1.2.3,<2.0.0
 - openbb-tradingeconomics >=1.3.3,<2.0.0
 - openbb-wsj >=1.3.3,<2.0.0
 - openbb-yfinance >=1.3.4,<2.0.0

**Comment by deeleeramone** [comment]
Hi there,

Please update your installation to use the latest versions. There was an issue with a previous version of yFinance because the response format was changed unexpectedly.

Additionally, error messages have improved since the version you are using. Unexpected Error will display the actual error type and message without having to enter debug mode.

**Comment by jjfantini** [comment]
ill update and see how this goes

**Comment by deeleeramone** [comment]
> ill update and see how this goes

All good?

**Comment by jjfantini** [comment]
@deeleeramone Yes, sorry! That seemed to fix the issue. I got distracted with some other dependency stuff, but all working now. Thanks for checking up, I really appreciate it.
