### ISSUE TITLE
[FR] Add a parameter to disable the startup prompt

### ISSUE THREAD

**Issue by bratfizyk** [OpenBB-finance/OpenBB#6991]
**What's the problem of not having this feature?**
I installed openbb-platform following the [docs (Docker section)](https://docs.openbb.co/platform/installation#docker).
Then I start it in interactive mode using the command from the docs:

```
docker run -it --rm -p 6900:6900 -v <my_path_to_settings>:/root/.openbb_platform openbb-platform:latest
```
(my_path_to_settings exists and I confirm that it contains the rigth files which are correctly mapped)

After a few seconds I see this screen, which expects me to press Enter.
![image](https://github.com/user-attachments/assets/84f2f349-6a14-4b68-9e44-a829381fbedc)

When I run the same container in a detached mode, it fails due to lack of an interactive session.
However, once I make sure the configuration file works as expected, I'd love to be able to start the container in a detached mode.

**Describe the solution you would like**
Two options:
* provide an ENV_VAR that disables the prompt (e.g. `DISABLE_PAT_PROMPT` with default value `0` in order to provide backward compatibility).
* automatically disable the prompt I presented in the screenshot if a user provided a valid configuration (this is however a change modifying the current behaviour, so some might consider it breaking).

**Describe alternatives you've considered**
I'd like to deploy `openbb-platofrm` in a Docker container to one of my virtual machines and use the REST-API from there. Without being able to disable the prompt, I need to ssh to my machine and start it manually, then potentially I need to keep the tty session up all the time. Not impossible, but inconvenient.

**Additional information**
I've started using openBB-platform recently so it might happen that I'm missing something fundamental here.

**Comment by deeleeramone** [comment]
You can disable the startup prompt with `openbb-api --no-login`

**Comment by bratfizyk** [comment]
I confirm that this worked for me. Thank you!
